### ISSUE TITLE
Dependencies of fast-http is wrong in /systems.txt

### ISSUE THREAD

**Issue by fukamachi** [quicklisp/quicklisp-controller#12]
I hope here is the right place to report this.

In the latest dist, no dependencies of fast-http are listed in [/systems.txt](http://beta.quicklisp.org/dist/quicklisp/2017-02-27/systems.txt) though it [depends on some](https://github.com/fukamachi/fast-http/blob/master/fast-http.asd#L18-L26).

Perhaps it because of [HANDLER-BIND issue](https://github.com/fukamachi/fast-http/issues/28), however, I think it's fixed before the release.

**Comment by xach** [comment]
Thank you for the report, it looks like this is a widespread issue, I will dig into it and fix.

**Comment by fukamachi** [comment]
I found it had already been fixed in the latest dist. Thanks!
