### ISSUE TITLE
Latest Quicklisp release broke Clon (cl-clon)

### ISSUE THREAD

**Issue by didierverna** [quicklisp/quicklisp-controller#20]
Hi,

this has been reported as a Clon github issue [here](https://github.com/didierverna/clon/issues/9) but I suppose it's related to the way the Quicklisp controller builds its metadata. The `net.didierverna.clon.termio` system has apparently disapeared from `system.txt` and `releases.txt`.

**Comment by quicklisp** [comment]
net.didierverna.clon.termio.asd can't be loaded in a fresh SBCL - it
contains a reference to a symbol in the sb-grovel package, causing a
package-not-found error. The defsystem-depends-on clause is evaluated too
late to matter.

I don't think this has anything to do with how Quicklisp builds things,
though I could definitely improve how I detect problems like these and
report them upstream.

**Comment by daewok** [comment]
@didierverna you probably want to use `("sb-grovel:grovel-constants-file" "sbcl/constants" :package :net.didierverna.clon)` as the component definition to avoid the read error. If the component type is a string, ASDF will attempt to `uiop:safe-read-from-string` it *after* the defsystem-depends-on dependencies have been loaded.

**Comment by didierverna** [comment]
Thanks. I'll wait for the next Quicklisp release and check before closing this.

**Comment by didierverna** [comment]
The new release of Clon didn't propagate to Quicklisp. I think this is because I forgot to push the new version tag to Github, along with the new commits.... Sorry :-(

**Comment by didierverna** [comment]
Hello,

the latest version of Clon still doesn't appear in today's release of Quicklisp. Is there something I need to do by hand to have it updated ?

Thanks.

**Comment by quicklisp** [comment]
Sorry about that. I will dig into it before the next release.

**Comment by quicklisp** [comment]
I take it you are not updating
https://www.lrde.epita.fr/~didier/software/lisp/clon/latest.tar.gz any
more? Should I use github now?

**Comment by didierverna** [comment]
Oh, I hadn't realized you were using that URL. Yes, it's preferable to use GitHub, thank you!

**Comment by didierverna** [comment]
Quicklisp finally has Clon back in, so I'm closing this. Thanks (I'm opening another issue tho ;-)).
